// --- Subject Module: COMMERCIAL AND TAXATION LAW ---

// 1. Syllabus Data
const COMM_TAX_SYLLABUS = [
    {id: 4001, topic: "1. BUSINESS ORGANIZATIONS", depth: 1, trackable: false},
    {id: 4002, topic: "1. Corporations – R.A. No. 11232", depth: 2, trackable: true},
    {id: 4003, topic: "1. Definition of Corporation", depth: 3, trackable: false},
    {id: 4004, topic: "2. Classes of Corporations", depth: 3, trackable: false},
    {id: 4005, topic: "3. Nationality of Corporations", depth: 3, trackable: false},
    {id: 4006, topic: "1. Control Test", depth: 4, trackable: false},
    {id: 4007, topic: "2. Grandfather Rule", depth: 4, trackable: false},
    {id: 4008, topic: "4. Juridical Personality", depth: 3, trackable: false},
    {id: 4009, topic: "1. Doctrine of Piercing the Corporate Veil", depth: 4, trackable: false},
    {id: 4010, topic: "5. Capital Structure", depth: 3, trackable: false},
    {id: 4011, topic: "1. Number and Qualifications of Incorporators", depth: 4, trackable: false},
    {id: 4012, topic: "2. Subscription Requirements", depth: 4, trackable: false},
    {id: 4013, topic: "3. Corporate Term", depth: 4, trackable: false},
    {id: 4014, topic: "4. Classification of Shares", depth: 4, trackable: false},
    {id: 4015, topic: "6. Incorporation and Organization", depth: 3, trackable: false},
    {id: 4016, topic: "1. Promoters", depth: 4, trackable: false},
    {id: 4017, topic: "Liability", depth: 5, trackable: false},
    {id: 4018, topic: "Liability of Corporation for Promoters' Contracts", depth: 5, trackable: false},
    {id: 4019, topic: "2. Subscription Contract", depth: 4, trackable: false},
    {id: 4020, topic: "3. Pre-incorporation Subscription Agreements", depth: 4, trackable: false},
    {id: 4021, topic: "4. Consideration for Stocks", depth: 4, trackable: false},
    {id: 4022, topic: "5. Articles of Incorporation", depth: 4, trackable: false},
    {id: 4023, topic: "6. Classification of Shares", depth: 4, trackable: false},
    {id: 4024, topic: "7. Corporate Name and Limitations on its Use", depth: 4, trackable: false},
    {id: 4025, topic: "8. Registration, Incorporation, and Commencement of Corporate Existence", depth: 4, trackable: false},
    {id: 4026, topic: "9. De Facto Corporation", depth: 4, trackable: false},
    {id: 4027, topic: "1. Corporation by Estoppel", depth: 5, trackable: false},
    {id: 4028, topic: "2. Election of Directors or Trustees", depth: 4, trackable: false},
    {id: 4029, topic: "i. By-laws", depth: 5, trackable: false},
    {id: 4030, topic: "j. Effects of Non-use of Corporate Charter", depth: 5, trackable: false},
    {id: 4031, topic: "1. Corporate Powers", depth: 3, trackable: false},
    {id: 4032, topic: "2. Stockholders and Members", depth: 3, trackable: false},
    {id: 4033, topic: "1. Doctrine of Equality of Shares", depth: 4, trackable: false},
    {id: 4034, topic: "2. Fundamental Rights of a Stockholder", depth: 4, trackable: false},
    {id: 4035, topic: "3. Participation in Management; Voting Requirements", depth: 4, trackable: false},
    {id: 4036, topic: "4. Stockholder's Rights", depth: 4, trackable: false},
    {id: 4037, topic: "5. Stockholder Suits", depth: 4, trackable: false},
    {id: 4038, topic: "6. Meetings", depth: 4, trackable: false},
    {id: 4039, topic: "3. Directors and Trustees", depth: 3, trackable: false},
    {id: 4040, topic: "1. Repository of Corporate Powers", depth: 4, trackable: false},
    {id: 4041, topic: "2. Tenure, Qualifications, and Disqualifications", depth: 4, trackable: false},
    {id: 4042, topic: "3. Independent Directors", depth: 4, trackable: false},
    {id: 4043, topic: "4. Election, Removal, and Filling of Vacancies", depth: 4, trackable: false},
    {id: 4044, topic: "5. Compensation", depth: 4, trackable: false},
    {id: 4045, topic: "6. Disloyalty", depth: 4, trackable: false},
    {id: 4046, topic: "7. Business Judgment Rule", depth: 4, trackable: false},
    {id: 4047, topic: "8. Liabilities and Responsibilities", depth: 4, trackable: false},
    {id: 4048, topic: "Special Fact Doctrine; Inside Information", depth: 5, trackable: false},
    {id: 4049, topic: "Directors Self-dealing with the Corporation", depth: 5, trackable: false},
    {id: 4050, topic: "Dealings between Corporations with Interlocking Directors", depth: 5, trackable: false},
    {id: 4051, topic: "4. Capital Affairs", depth: 3, trackable: false},
    {id: 4052, topic: "1. Certificate of Stock", depth: 4, trackable: false},
    {id: 4053, topic: "2. Watered Stocks", depth: 4, trackable: false},
    {id: 4054, topic: "Definition", depth: 5, trackable: false},
    {id: 4055, topic: "Liability of Directors", depth: 5, trackable: false},
    {id: 4056, topic: "3. Trust Fund Doctrine", depth: 4, trackable: false},
    {id: 4057, topic: "4. Payment of Balance of Subscription", depth: 4, trackable: false},
    {id: 4058, topic: "5. Sale of Delinquent Shares", depth: 4, trackable: false},
    {id: 4059, topic: "6. Transfer of Shares", depth: 4, trackable: false},
    {id: 4060, topic: "7. Corporate Books and Records", depth: 4, trackable: false},
    {id: 4061, topic: "7. Securities – R.A. No. 8799", depth: 3, trackable: false},
    {id: 4062, topic: "1. Regulatory Framework – Secs. 8-10", depth: 4, trackable: false},
    {id: 4063, topic: "2. Definition of Security; Howey Test – Sec. 3", depth: 4, trackable: false},
    {id: 4064, topic: "3. Registration of Securities", depth: 4, trackable: false},
    {id: 4065, topic: "1. Exempt Securities", depth: 5, trackable: false},
    {id: 4066, topic: "2. Exempt Transactions", depth: 5, trackable: false},
    {id: 4067, topic: "5. Merger, Consolidation, and Acquisition – relate to R.A. No. 10667", depth: 3, trackable: false},
    {id: 4068, topic: "1. Concept – Sec. 4", depth: 4, trackable: false},
    {id: 4069, topic: "1. Asset-only and Business Enterprise Transfers", depth: 5, trackable: false},
    {id: 4070, topic: "2. Review – Sec. 16", depth: 4, trackable: false},
    {id: 4071, topic: "1.Compulsory Notification – Secs. 17-19", depth: 5, trackable: false},
    {id: 4072, topic: "2. Prohibited Mergers and Acquisitions – Secs. 20-22", depth: 5, trackable: false},
    {id: 4073, topic: "3. Effects", depth: 4, trackable: false},
    {id: 4074, topic: "6. Corporate Dissolution and Liquidation", depth: 3, trackable: false},
    {id: 4075, topic: "7. Foreign Corporations", depth: 3, trackable: false},
    {id: 4076, topic: "1. Suability and Personality to Sue", depth: 4, trackable: false},
    {id: 4077, topic: "2. Foreign Investments – R.A. No. 7042, as amended by R.A. No. 8179 and R.A. No. 11647", depth: 4, trackable: false},
    {id: 4078, topic: "1. Doing Business in the Philippines", depth: 5, trackable: false},
    {id: 4079, topic: "2. Definition of Foreign Investment", depth: 5, trackable: false},
    {id: 4080, topic: "3. Registration Requirement", depth: 5, trackable: false},
    {id: 4081, topic: "4. Nationalized Activities and the Negative List", depth: 5, trackable: false},
    {id: 4082, topic: "8. Special Corporations", depth: 3, trackable: false},
    {id: 4083, topic: "1. Close Corporations", depth: 4, trackable: false},
    {id: 4084, topic: "2. Non-stock Corporations", depth: 4, trackable: false},
    {id: 4085, topic: "3. Educational Corporations", depth: 4, trackable: false},
    {id: 4086, topic: "4. Religious Corporations", depth: 4, trackable: false},
    {id: 4087, topic: "5. One Person Corporations", depth: 4, trackable: false},
    {id: 4088, topic: "1. Excepted Corporations", depth: 5, trackable: false},
    {id: 4089, topic: "2. Capital Stock Requirement", depth: 5, trackable: false},
    {id: 4090, topic: "3. Articles of Incorporation and By-laws", depth: 5, trackable: false},
    {id: 4091, topic: "4. Corporate Name", depth: 5, trackable: false},
    {id: 4092, topic: "5. Corporate Structure and Officers", depth: 5, trackable: false},
    {id: 4093, topic: "6. Nominee", depth: 5, trackable: false},
    {id: 4094, topic: "7. Liability", depth: 5, trackable: false},
    {id: 4095, topic: "8. Conversion of Corporation", depth: 5, trackable: false},
    {id: 4096, topic: "2. Partnerships", depth: 2, trackable: true},
    {id: 4097, topic: "1. General Provisions", depth: 3, trackable: false},
    {id: 4098, topic: "1. Definition and Separate Juridical Personality", depth: 4, trackable: false},
    {id: 4099, topic: "2. Rules to Determine Existence", depth: 4, trackable: false},
    {id: 4100, topic: "3. Separate Juridical Personality", depth: 4, trackable: false},
    {id: 4101, topic: "4. Partnership by Estoppel", depth: 4, trackable: false},
    {id: 4102, topic: "5. Kinds of Partnership", depth: 4, trackable: false},
    {id: 4103, topic: "2. Obligations of Partners among Themselves", depth: 3, trackable: false},
    {id: 4104, topic: "3. Property Rights of Partners", depth: 3, trackable: false},
    {id: 4105, topic: "4. Obligations of Partnership; Obligations of Partners to Third Persons", depth: 3, trackable: false},
    {id: 4106, topic: "5. Dissolution and Winding Up", depth: 3, trackable: false},
    {id: 4107, topic: "3. INSURANCE – P.D. No. 612, as amended by R.A. No. 10607", depth: 2, trackable: true},
    {id: 4108, topic: "1. Concept of Insurance", depth: 3, trackable: false},
    {id: 4109, topic: "2. Insurable Interest", depth: 3, trackable: false},
    {id: 4110, topic: "3. Concealment", depth: 3, trackable: false},
    {id: 4111, topic: "4. Representation", depth: 3, trackable: false},
    {id: 4112, topic: "5. Policy", depth: 3, trackable: false},
    {id: 4113, topic: "6. Warranties", depth: 3, trackable: false},
    {id: 4114, topic: "7. Premium", depth: 3, trackable: false},
    {id: 4115, topic: "8. Loss", depth: 3, trackable: false},
    {id: 4116, topic: "9. Notice and Proof of Loss", depth: 3, trackable: false},
    {id: 4117, topic: "10. Double Insurance and Overinsurance", depth: 3, trackable: false},
    {id: 4118, topic: "11. Reinsurance", depth: 3, trackable: false},
    {id: 4119, topic: "12. Rescission of Insurance Contracts", depth: 3, trackable: false},
    {id: 4120, topic: "4. TRANSPORTATION", depth: 2, trackable: true},
    {id: 4121, topic: "1. Common Carriers", depth: 3, trackable: false},
    {id: 4122, topic: "1. Common Carrier v. Private Carrier", depth: 4, trackable: false},
    {id: 4123, topic: "2. Diligence Required", depth: 4, trackable: false},
    {id: 4124, topic: "3. Transport Network Services", depth: 4, trackable: false},
    {id: 4125, topic: "4. Defenses Available to a Common Carrier", depth: 4, trackable: false},
    {id: 4126, topic: "2. Vigilance over Goods", depth: 3, trackable: false},
    {id: 4127, topic: "1. Under the Civil Code", depth: 4, trackable: false},
    {id: 4128, topic: "2. Under the Montreal Convention", depth: 4, trackable: false},
    {id: 4129, topic: "3. Under the Carriage of Goods by Sea Act", depth: 4, trackable: false},
    {id: 4130, topic: "3. Safety of Passengers", depth: 3, trackable: false},
    {id: 4131, topic: "1. Under the Civil Code", depth: 4, trackable: false},
    {id: 4132, topic: "2. Under the Montreal Convention", depth: 4, trackable: false},
    {id: 4133, topic: "3. Under the Carriage of Goods by Sea Act", depth: 4, trackable: false},
    {id: 4134, topic: "5. BANKING", depth: 2, trackable: true},
    {id: 4135, topic: "1. Secrecy of Bank Deposits – R.A. No. 1405 and R.A. No. 6426, as amended", depth: 3, trackable: false},
    {id: 4136, topic: "1. Purpose", depth: 4, trackable: false},
    {id: 4137, topic: "2. Prohibited Acts", depth: 4, trackable: false},
    {id: 4138, topic: "3. Coverage and Exceptions", depth: 4, trackable: false},
    {id: 4139, topic: "4. Garnishment of Deposits, including Foreign Deposits", depth: 4, trackable: false},
    {id: 4140, topic: "2. General Banking Law – R.A. No. 8791", depth: 3, trackable: false},
    {id: 4141, topic: "1. Definition and Classification of Banks", depth: 4, trackable: false},
    {id: 4142, topic: "2. Distinction among Banks, Quasi-banks, and Trust Entities", depth: 4, trackable: false},
    {id: 4143, topic: "3. Nature of Bank Funds and Bank Deposits", depth: 4, trackable: false},
    {id: 4144, topic: "4. Diligence Required of Banks", depth: 4, trackable: false},
    {id: 4145, topic: "5. Prohibited Transactions by Bank Directors, Officers, and Employees", depth: 4, trackable: false},
    {id: 4146, topic: "6. Stipulation on Interest", depth: 4, trackable: false},
    {id: 4147, topic: "3. Deposit Insurance – R.A. No. 3591, as amended by R.A. No. 11840", depth: 3, trackable: false},
    {id: 4148, topic: "1. Definition of Insured Deposit", depth: 4, trackable: false},
    {id: 4149, topic: "2. Deposit Insurance Coverage", depth: 4, trackable: false},
    {id: 4150, topic: "3. Splitting of Deposits", depth: 4, trackable: false},
    {id: 4151, topic: "4. Anti-Money Laundering – R.A. No. 9160, as amended by R.A. No. 9194, R.A. No. 10167, R.A. No. 10365, R.A. No. 10927, and R.A. No.11521", depth: 3, trackable: false},
    {id: 4152, topic: "A. Policy", depth: 4, trackable: false},
    {id: 4153, topic: "B. Covered Institutions and their Obligations", depth: 4, trackable: false},
    {id: 4154, topic: "C. Covered Transactions", depth: 4, trackable: false},
    {id: 4155, topic: "D. Suspicious Transactions", depth: 4, trackable: false},
    {id: 4156, topic: "E. Safe Harbor Provision", depth: 4, trackable: false},
    {id: 4157, topic: "F. Money Laundering", depth: 4, trackable: false},
    {id: 4158, topic: "1. How Committed", depth: 5, trackable: false},
    {id: 4159, topic: "2. Predicate Crimes or Unlawful Activity", depth: 5, trackable: false},
    {id: 4160, topic: "G. Authority to Inquire, Freezing, and Forfeiture", depth: 4, trackable: false},
    {id: 4161, topic: "5. The Central Bank – R.A. No. 7653, as amended by R.A. No. 11211", depth: 3, trackable: false},
    {id: 4162, topic: "1. State Policies", depth: 4, trackable: false},
    {id: 4163, topic: "2. Powers and Functions of the Monetary Board", depth: 4, trackable: false},
    {id: 4164, topic: "3. Banks in Distress", depth: 4, trackable: false},
    {id: 4165, topic: "1. Conservatorship", depth: 5, trackable: false},
    {id: 4166, topic: "2. Closure", depth: 5, trackable: false},
    {id: 4167, topic: "3. Receivership", depth: 5, trackable: false},
    {id: 4168, topic: "4. Liquidation", depth: 5, trackable: false},
    {id: 4169, topic: "6. INTELLECTUAL PROPERTY – R.A. No. 8293, as amended by R.A. No. 9150, R.A. No. 9502, and R.A. No. 10372", depth: 2, trackable: true},
    {id: 4170, topic: "1. Patents", depth: 3, trackable: false},
    {id: 4171, topic: "1. Patentable v. Non-patentable Inventions", depth: 4, trackable: false},
    {id: 4172, topic: "2. Ownership of a Patent", depth: 4, trackable: false},
    {id: 4173, topic: "3. Rights Conferred", depth: 4, trackable: false},
    {id: 4174, topic: "4. Limitations", depth: 4, trackable: false},
    {id: 4175, topic: "5. Infringement", depth: 4, trackable: false},
    {id: 4176, topic: "6. Cancellation", depth: 4, trackable: false},
    {id: 4177, topic: "7. True and Actual Inventor's Remedy", depth: 4, trackable: false},
    {id: 4178, topic: "8. Licensing", depth: 4, trackable: false},
    {id: 4179, topic: "9. Assignment and Transmission of Rights", depth: 4, trackable: false},
    {id: 4180, topic: "2. Trademarks", depth: 3, trackable: false},
    {id: 4181, topic: "1. Marks v. Collective Marks v. Trade Names", depth: 4, trackable: false},
    {id: 4182, topic: "2. Acquisition of Ownership", depth: 4, trackable: false},
    {id: 4183, topic: "3. Non-registrable Marks", depth: 4, trackable: false},
    {id: 4184, topic: "4. Ownership, Registration, and Duration", depth: 4, trackable: false},
    {id: 4185, topic: "5. Confusing Similarity", depth: 4, trackable: false},
    {id: 4186, topic: "6. Well-known Marks", depth: 4, trackable: false},
    {id: 4187, topic: "7. Rights Conferred by Registration", depth: 4, trackable: false},
    {id: 4188, topic: "8. Infringement", depth: 4, trackable: false},
    {id: 4189, topic: "9. Unfair Competition", depth: 4, trackable: false},
    {id: 4190, topic: "10. Cancellation", depth: 4, trackable: false},
    {id: 4191, topic: "3. Copyright", depth: 3, trackable: false},
    {id: 4192, topic: "1. Basic Principles – Secs. 172.2, 175, and 181", depth: 4, trackable: false},
    {id: 4193, topic: "2. Copyrightable Works", depth: 4, trackable: false},
    {id: 4194, topic: "3. Non-copyrightable Works", depth: 4, trackable: false},
    {id: 4195, topic: "4. Rights Conferred by Copyright", depth: 4, trackable: false},
    {id: 4196, topic: "5. Ownership of a Copyright", depth: 4, trackable: false},
    {id: 4197, topic: "6. Limitations on Copyright", depth: 4, trackable: false},
    {id: 4198, topic: "7. Fair Use", depth: 4, trackable: false},
    {id: 4199, topic: "8. Copyright Infringement", depth: 4, trackable: false},
    {id: 4200, topic: "4. SPECIAL COMMERCIAL LAWS", depth: 2, trackable: true},
    {id: 4201, topic: "1. R.A. No. 10142 (Financial Rehabilitation and Insolvency Act)", depth: 3, trackable: false},
    {id: 4202, topic: "1. Definition of Insolvent", depth: 4, trackable: false},
    {id: 4203, topic: "2. Rehabilitation", depth: 4, trackable: false},
    {id: 4204, topic: "1. Key Concepts", depth: 5, trackable: false},
    {id: 4205, topic: "2. Effects of Commencement Order and Exceptions", depth: 5, trackable: false},
    {id: 4206, topic: "3. Cram Down Effect", depth: 5, trackable: false},
    {id: 4207, topic: "3. Liquidation and Effects of Liquidation Order", depth: 4, trackable: false},
    {id: 4208, topic: "4. Suspension of Payments", depth: 4, trackable: false},
    {id: 4209, topic: "2. R.A. No. 8792 (Electronic Commerce Act)", depth: 3, trackable: false},
    {id: 4210, topic: "1. Legal Recognition of Electronic Data Messages, Documents, and Signatures – Secs. 6-11", depth: 4, trackable: false},
    {id: 4211, topic: "2. Lawful Access and Obligation of Confidentiality – Sec. 32", depth: 4, trackable: false},
    {id: 4212, topic: "3. Commonwealth Act No. 146, as amended by R.A. No. 11659 (Public Service Act)", depth: 3, trackable: false},
    {id: 4213, topic: "1. Critical Infrastructure – R.A. No. 11659, Sec. 2(e)", depth: 4, trackable: false},
    {id: 4214, topic: "2. Foreign State-owned Enterprise – R.A. No. 11659, Sec. 2(g)", depth: 4, trackable: false},
    {id: 4215, topic: "3. Public Service as Public Utility – R.A. No. 11659, Sec. 4", depth: 4, trackable: false},
    {id: 4216, topic: "4. Unlawful Acts – R.A. No. 11659, Sec. 9", depth: 4, trackable: false},
    {id: 4217, topic: "5. Suspensive and Prohibitory Powers of the President – R.A. No. 11659, Sec. 23", depth: 4, trackable: false},
    {id: 4218, topic: "6. Investments by an Entity Controlled by or Acting on Behalf of a Foreign Government, or Foreign State-Owned Enterprises – R.A. No. 11659, Sec. 24", depth: 4, trackable: false},
    {id: 4219, topic: "7. Reciprocity Clause – R.A. No. 11659, Sec. 25", depth: 4, trackable: false},
    {id: 4220, topic: "4. R.A. No. 10667 (Philippine Competition Act)", depth: 3, trackable: false},
    {id: 4221, topic: "1. Definitions and Scope of Application – Sec. 4", depth: 4, trackable: false},
    {id: 4222, topic: "2. Prohibited Acts", depth: 4, trackable: false},
    {id: 4223, topic: "1. Anti-competitive Agreements – Sec. 14", depth: 5, trackable: false},
    {id: 4224, topic: "1. Per Se Violations", depth: 6, trackable: false},
    {id: 4225, topic: "2. Not Per Se Violations", depth: 6, trackable: false},
    {id: 4226, topic: "2. Abuse of Dominant Position – Sec. 15", depth: 5, trackable: false},
    {id: 4227, topic: "3. Determining the Relevant Market – Secs. 4(k) and 24", depth: 4, trackable: false},
    {id: 4228, topic: "4. Determining Control or Dominance of Market – Secs. 25 and 27", depth: 4, trackable: false},
    {id: 4229, topic: "5. Determining Existence of Anti-competitive Conduct – Sec. 26", depth: 4, trackable: false},
    {id: 4230, topic: "VIII. TAXATION LAW", depth: 1, trackable: false},
    {id: 4231, topic: "1. General Principles", depth: 2, trackable: true},
    {id: 4232, topic: "1. Concept and Definition of Taxation", depth: 3, trackable: false},
    {id: 4233, topic: "2. Inherent and Constitutional Limitations of Taxation", depth: 3, trackable: false},
    {id: 4234, topic: "3. Requisites of a Valid Tax", depth: 3, trackable: false},
    {id: 4235, topic: "4. Lifeblood Doctrine; Manifestations; Prohibition on Compensation and Set-off, Impact, and Effect", depth: 3, trackable: false},
    {id: 4236, topic: "5. Authority of Congress, Secretary of Finance, and Commissioner of Internal Revenue (CIR)", depth: 3, trackable: false},
    {id: 4237, topic: "6. Construction and Interpretation of Tax Laws, Rules, and Regulations", depth: 3, trackable: false},
    {id: 4238, topic: "7. Double Taxation", depth: 3, trackable: false},
    {id: 4239, topic: "8. Escape from Taxation", depth: 3, trackable: false},
    {id: 4240, topic: "9. Tax Exemption", depth: 3, trackable: false},
    {id: 4241, topic: "10. Compromise and Tax Amnesty", depth: 3, trackable: false},
    {id: 4242, topic: "11. Taxpayer’s Suit: Rationale and Requisites", depth: 3, trackable: false},
    {id: 4243, topic: "2. National Taxation – National Internal Revenue Code of 1997 [NIRC], as amended", depth: 2, trackable: true},
    {id: 4244, topic: "1. Jurisdiction, Powers, and Functions of the Bureau of Internal Revenue", depth: 3, trackable: false},
    {id: 4245, topic: "2. Income Tax", depth: 3, trackable: false},
    {id: 4246, topic: "1. Nature and General Principles", depth: 4, trackable: false},
    {id: 4247, topic: "1.Criteria in Imposing Philippine Income Tax", depth: 5, trackable: false},
    {id: 4248, topic: "2. Kinds of Taxpayers", depth: 5, trackable: false},
    {id: 4249, topic: "2. Income", depth: 4, trackable: false},
    {id: 4250, topic: "1. Definition", depth: 5, trackable: false},
    {id: 4251, topic: "2. Realization and Recognition", depth: 5, trackable: false},
    {id: 4252, topic: "3. Taxability", depth: 5, trackable: false},
    {id: 4253, topic: "4. Sources", depth: 5, trackable: false},
    {id: 4254, topic: "1. Compensation Income", depth: 6, trackable: false},
    {id: 4255, topic: "2. Professional Income", depth: 6, trackable: false},
    {id: 4256, topic: "3. Income from Business", depth: 6, trackable: false},
    {id: 4257, topic: "1. Active v. Passive Income", depth: 7, trackable: false},
    {id: 4258, topic: "4. Income from Dealings in Property", depth: 6, trackable: false},
    {id: 4259, topic: "1. Capital v. Ordinary Asset", depth: 7, trackable: false},
    {id: 4260, topic: "5. Situs of Income Taxation", depth: 5, trackable: false},
    {id: 4261, topic: "6. Gross Income v. Net Income v. Taxable Income", depth: 5, trackable: false},
    {id: 4262, topic: "1. Tax Deductions v. Tax Credits", depth: 6, trackable: false},
    {id: 4263, topic: "2. Optional Standard Deduction", depth: 6, trackable: false},
    {id: 4264, topic: "7. Withholding Taxes", depth: 5, trackable: false},
    {id: 4265, topic: "1. Rationale", depth: 6, trackable: false},
    {id: 4266, topic: "2. Creditable v. Withholding Taxes", depth: 6, trackable: false},
    {id: 4267, topic: "3. Duties of a Withholding Agent", depth: 6, trackable: false},
    {id: 4268, topic: "3. Value-Added Tax (VAT)", depth: 3, trackable: false},
    {id: 4269, topic: "1. Concept", depth: 4, trackable: false},
    {id: 4270, topic: "2. Elements of Transaction Subject to VAT", depth: 4, trackable: false},
    {id: 4271, topic: "3. Impact and Incidence of Tax", depth: 4, trackable: false},
    {id: 4272, topic: "4. Destination Principle; Cross-Border Doctrine", depth: 4, trackable: false},
    {id: 4273, topic: "5. Transactions Deemed Sale Subject to VAT", depth: 4, trackable: false},
    {id: 4274, topic: "6. Zero-rated Transactions", depth: 4, trackable: false},
    {id: 4275, topic: "7. VAT Exempt Persons v. VAT Exempt Transactions", depth: 4, trackable: false},
    {id: 4276, topic: "8. Input and Output Tax", depth: 4, trackable: false},
    {id: 4277, topic: "9. Tax Refund or Tax Credit", depth: 4, trackable: false},
    {id: 4278, topic: "4. Estate Tax (Basic Principles and Concepts only)", depth: 3, trackable: false},
    {id: 4279, topic: "5. Donor’s Tax (Basic Principles and Concepts only)", depth: 3, trackable: false},
    {id: 4280, topic: "6. Tax Remedies under the NIRC", depth: 3, trackable: false},
    {id: 4281, topic: "1. General Concepts", depth: 4, trackable: false},
    {id: 4282, topic: "1. Tax Deficiency v. Tax Delinquency", depth: 5, trackable: false},
    {id: 4283, topic: "2. Tax Evasion", depth: 5, trackable: false},
    {id: 4284, topic: "2. Civil Penalties", depth: 4, trackable: false},
    {id: 4285, topic: "1. Deficiency Interest and Delinquency Interest", depth: 5, trackable: false},
    {id: 4286, topic: "2. Surcharge", depth: 5, trackable: false},
    {id: 4287, topic: "3. Compromise Penalty", depth: 5, trackable: false},
    {id: 4288, topic: "3. Assessment Process", depth: 4, trackable: false},
    {id: 4289, topic: "1. Letter of Authority", depth: 5, trackable: false},
    {id: 4290, topic: "2. Submission of Supporting Documents by Taxpayer", depth: 5, trackable: false},
    {id: 4291, topic: "3. Notice of Discrepancy", depth: 5, trackable: false},
    {id: 4292, topic: "4. Issuance of Preliminary Assessment Notice", depth: 5, trackable: false},
    {id: 4293, topic: "5. Issuance of Formal Letter of Demand or Final Assessment Notice", depth: 5, trackable: false},
    {id: 4294, topic: "1. Prescriptive Period for Assessment", depth: 6, trackable: false},
    {id: 4295, topic: "1. False Return v. Fraudulent Return v. Non-filing", depth: 7, trackable: false},
    {id: 4296, topic: "2. Suspension of the Running of Statute of Limitations", depth: 7, trackable: false},
    {id: 4297, topic: "4. Collection Process", depth: 4, trackable: false},
    {id: 4298, topic: "1. Requisites", depth: 5, trackable: false},
    {id: 4299, topic: "2. Prescriptive Periods", depth: 5, trackable: false},
    {id: 4300, topic: "5. Taxpayers' Remedies", depth: 4, trackable: false},
    {id: 4301, topic: "1. Protesting an Assessment", depth: 5, trackable: false},
    {id: 4302, topic: "1. Period to File Protest", depth: 6, trackable: false},
    {id: 4303, topic: "2. Effect of Failure to File Protest", depth: 6, trackable: false},
    {id: 4304, topic: "2. Submission of Supporting Documents by Taxpayer", depth: 5, trackable: false},
    {id: 4305, topic: "3. Decision of the Commissioner on the Protest", depth: 5, trackable: false},
    {id: 4306, topic: "1. Period to Act Upon or Decide", depth: 6, trackable: false},
    {id: 4307, topic: "2. Remedies in Case of CIR’s Denial or Failure to Act", depth: 6, trackable: false},
    {id: 4308, topic: "3. Effect of Failure to Appeal", depth: 6, trackable: false},
    {id: 4309, topic: "4. Compromise and Abatement of Taxes", depth: 5, trackable: false},
    {id: 4310, topic: "5. Recovery of Tax Erroneously or Illegally Collected", depth: 5, trackable: false},
    {id: 4311, topic: "1. Grounds, Requisites, and Period for Filing a Claim for Refund or Issuance of a Tax Credit Certificate", depth: 6, trackable: false},
    {id: 4312, topic: "2. Proper Party to File Claim for Refund or Tax Credit", depth: 6, trackable: false},
    {id: 4313, topic: "6. Government Remedies", depth: 4, trackable: false},
    {id: 4314, topic: "1. Administrative Remedies", depth: 5, trackable: false},
    {id: 4315, topic: "1. Tax Lien", depth: 6, trackable: false},
    {id: 4316, topic: "2. Distraint and Levy", depth: 6, trackable: false},
    {id: 4317, topic: "3. Forfeiture of Real Property", depth: 6, trackable: false},
    {id: 4318, topic: "4. Suspension of Business Operation", depth: 6, trackable: false},
    {id: 4319, topic: "2. Judicial Remedies", depth: 5, trackable: false},
    {id: 4320, topic: "1. Civil Action", depth: 6, trackable: false},
    {id: 4321, topic: "2. Criminal Action", depth: 6, trackable: false},
    {id: 4322, topic: "3. Local Taxation – R.A. No. 7160", depth: 2, trackable: true},
    {id: 4323, topic: "1. General Principles – Secs. 130 and 132", depth: 3, trackable: false},
    {id: 4324, topic: "2. Common Limitations on the Taxing Powers of Local Government Units – Sec. 133", depth: 3, trackable: false},
    {id: 4325, topic: "3. Validity of Local Tax Ordinance – Sec. 187", depth: 3, trackable: false},
    {id: 4326, topic: "4. Assessment and Collection of Local Taxes", depth: 3, trackable: false},
    {id: 4327, topic: "1. Remedies of Local Government Units", depth: 4, trackable: false},
    {id: 4328, topic: "2. Prescriptive Period", depth: 4, trackable: false},
    {id: 4329, topic: "3. Injunction", depth: 4, trackable: false},
    {id: 4330, topic: "5. Taxpayers' Remedies", depth: 3, trackable: false},
    {id: 4331, topic: "1. Protest – Sec. 195", depth: 4, trackable: false},
    {id: 4332, topic: "2. Refund or Credit – Sec. 196", depth: 4, trackable: false},
    {id: 4333, topic: "3. Court Action", depth: 4, trackable: false},
    {id: 4334, topic: "6. Local Taxes", depth: 3, trackable: false},
    {id: 4335, topic: "1. Professional Tax – Sec. 139", depth: 4, trackable: false},
    {id: 4336, topic: "2. Local Business Tax – Secs. 143, 145, and 146", depth: 4, trackable: false},
    {id: 4337, topic: "3. Community Tax – Secs. 157-160", depth: 4, trackable: false},
    {id: 4338, topic: "4. Real Property Taxation (Book II, Title II)", depth: 4, trackable: false},
    {id: 4339, topic: "1. Fundamental Principles; Nature; Power to Levy", depth: 5, trackable: false},
    {id: 4340, topic: "2. Exemption from Real Property Tax – Sec. 234", depth: 5, trackable: false},
    {id: 4341, topic: "3. Appraisal and Assessment", depth: 5, trackable: false},
    {id: 4342, topic: "4. Collection", depth: 5, trackable: false},
    {id: 4343, topic: "5. Taxpayers' Remedies", depth: 5, trackable: false},
    {id: 4344, topic: "1. Against Assessment", depth: 6, trackable: false},
    {id: 4345, topic: "1. Payment Under Protest; Exceptions", depth: 7, trackable: false},
    {id: 4346, topic: "2. Compromise of Assessment", depth: 7, trackable: false},
    {id: 4347, topic: "2. Against Valuation of Property", depth: 6, trackable: false},
    {id: 4348, topic: "4. Judicial Remedies", depth: 5, trackable: false},
    {id: 4349, topic: "1. Appeal to the Local Board of Assessment Appeals", depth: 6, trackable: false},
    {id: 4350, topic: "2. Appeal to the Central Board of Assessment Appeals", depth: 6, trackable: false},
    {id: 4351, topic: "3. Effect of Payment of Taxes", depth: 6, trackable: false},
    {id: 4352, topic: "4. Court of Tax Appeals (CTA)", depth: 2, trackable: true},
    {id: 4353, topic: "1. Exclusive Original and Appellate Jurisdiction Over Civil Cases", depth: 3, trackable: false},
    {id: 4354, topic: "2. Exclusive Original and Appellate Jurisdiction Over Criminal Cases", depth: 3, trackable: false},
    {id: 4355, topic: "2. Procedures", depth: 3, trackable: false},
    {id: 4356, topic: "1. Action for Collection of Taxes", depth: 4, trackable: false},
    {id: 4357, topic: "1. National Taxes", depth: 5, trackable: false},
    {id: 4358, topic: "2. Local Taxes", depth: 5, trackable: false},
    {id: 4359, topic: "2. Civil Cases", depth: 4, trackable: false},
    {id: 4360, topic: "1. Who May Appeal, Mode of Appeal, and Effect of Appeal", depth: 5, trackable: false},
    {id: 4361, topic: "2. Suspension of Collection of Taxes", depth: 5, trackable: false},
    {id: 4362, topic: "3. Injunction Not Available to Restrain Tax Collection", depth: 5, trackable: false},
    {id: 4363, topic: "3. Criminal Cases", depth: 4, trackable: false},
    {id: 4364, topic: "1. Institution and Prosecution of Criminal Action", depth: 5, trackable: false},
    {id: 4365, topic: "2. Institution of Civil Action in Criminal Action", depth: 5, trackable: false},
    {id: 4366, topic: "ii. Period to Appeal", depth: 5, trackable: false},
    {id: 4367, topic: "4. Appeal to the CTA En Banc", depth: 4, trackable: false},
    {id: 4368, topic: "5. Petition for Review on Certiorari to the Supreme Court", depth: 4, trackable: false}
];

// 2. Storage Key and Subject Details
const SYLLABUS_STORAGE_KEY_COMM = 'comm_tax_progress';
const SUBJECT_NAME_COMM = 'comm';
const SUBJECT_TITLE_COMM = 'COMMERCIAL AND TAXATION LAWS';
const SUBJECT_ICON_COMM = 'banknote';

// 3. Create Logic Instance
// This calls the global factory defined in index.html
const COMM_LOGIC = window.createSyllabusLogic(SUBJECT_NAME_COMM, COMM_TAX_SYLLABUS, SYLLABUS_STORAGE_KEY_COMM, SUBJECT_ICON_COMM, SUBJECT_TITLE_COMM);

// 4. Inject Panel HTML into the main container in index.html
document.addEventListener('DOMContentLoaded', () => {
    const container = document.getElementById('subject-trackers-container');
    if (container) {
        // Only inject if the base logic module hasn't already done it (prevents duplication during load)
        if (!document.getElementById(`subject-tracker-panel-${SUBJECT_NAME_COMM}`)) {
            container.innerHTML += COMM_LOGIC.getPanelHtml(SUBJECT_NAME_COMM, SUBJECT_TITLE_COMM, SUBJECT_ICON_COMM);
        }
    }
});

// 5. Expose Logic Globally (needed for index.html onload to attach to map)
window.createCOMM_LOGIC = () => COMM_LOGIC;
