// --- Subject Module: COMMERCIAL AND TAXATION LAW ---

// 1. Syllabus Data
const COMM_TAX_SYLLABUS = [
    {id: 4001, topic: 'I. BUSINESS ORGANIZATIONS', depth: 1, trackable: true},
    {id: 4002, topic: 'A. Corporations – R.A. No. 11232', depth: 2, trackable: true},
    {id: 4003, topic: '1. Definition, Classes, and Nationality', depth: 3, trackable: true},
    {id: 4004, topic: 'a. Definition of Corporation', depth: 4, trackable: false},
    {id: 4005, topic: 'b. Classes of Corporations', depth: 4, trackable: false},
    {id: 4006, topic: 'c. Nationality of Corporations', depth: 4, trackable: false},
    {id: 4007, topic: 'i. Control Test', depth: 5, trackable: false},
    {id: 4008, topic: 'ii. Grandfather Rule', depth: 5, trackable: false},
    {id: 4009, topic: '2. Juridical Personality and Piercing the Corporate Veil', depth: 3, trackable: true},
    {id: 4010, topic: '3. Capital Structure', depth: 3, trackable: true},
    {id: 4011, topic: 'a. Number and Qualifications of Incorporators', depth: 4, trackable: false},
    {id: 4012, topic: 'b. Subscription Requirements', depth: 4, trackable: false},
    {id: 4013, topic: 'c. Corporate Term', depth: 4, trackable: false},
    {id: 4014, topic: 'd. Classification of Shares', depth: 4, trackable: false},
    {id: 4015, topic: '4. Incorporation and Organization', depth: 3, trackable: true},
    {id: 4016, topic: 'a. Promoters', depth: 4, trackable: false},
    {id: 4017, topic: 'i. Liability', depth: 5, trackable: false},
    {id: 4018, topic: 'ii. Liability of Corporation for Promoters\' Contracts', depth: 5, trackable: false},
    {id: 4019, topic: 'b. Subscription Contract', depth: 4, trackable: false},
    {id: 4020, topic: 'c. Pre-incorporation Subscription Agreements', depth: 4, trackable: false},
    {id: 4021, topic: 'd. Consideration for Stocks', depth: 4, trackable: false},
    {id: 4022, topic: 'e. Articles of Incorporation', depth: 4, trackable: false},
    {id: 4023, topic: 'f. Corporate Name and Limitations on its Use', depth: 4, trackable: false},
    {id: 4024, topic: 'g. Registration, Incorporation, and Commencement of Corporate Existence', depth: 4, trackable: false},
    {id: 4025, topic: 'h. De Facto Corporation', depth: 4, trackable: false},
    {id: 4026, topic: 'i. Corporation by Estoppel', depth: 5, trackable: false},
    {id: 4027, topic: 'j. Election of Directors or Trustees', depth: 4, trackable: false},
    {id: 4028, topic: 'k. By-laws', depth: 5, trackable: false},
    {id: 4029, topic: 'l. Effects of Non-use of Corporate Charter', depth: 5, trackable: false},
    {id: 4030, topic: '5. Corporate Powers', depth: 3, trackable: true},
    {id: 4031, topic: '6. Stockholders and Members', depth: 3, trackable: true},
    {id: 4032, topic: 'a. Doctrine of Equality of Shares', depth: 4, trackable: false},
    {id: 4033, topic: 'b. Fundamental Rights of a Stockholder', depth: 4, trackable: false},
    {id: 4034, topic: 'c. Participation in Management; Voting Requirements', depth: 4, trackable: false},
    {id: 4035, topic: 'd. Stockholder\'s Rights', depth: 4, trackable: false},
    {id: 4036, topic: 'e. Stockholder Suits', depth: 4, trackable: false},
    {id: 4037, topic: 'f. Meetings', depth: 4, trackable: false},
    {id: 4038, topic: '7. Directors and Trustees', depth: 3, trackable: true},
    {id: 4039, topic: 'a. Repository of Corporate Powers', depth: 4, trackable: false},
    {id: 4040, topic: 'b. Tenure, Qualifications, and Disqualifications', depth: 4, trackable: false},
    {id: 4041, topic: 'c. Independent Directors', depth: 4, trackable: false},
    {id: 4042, topic: 'd. Election, Removal, and Filling of Vacancies', depth: 4, trackable: false},
    {id: 4043, topic: 'e. Compensation', depth: 4, trackable: false},
    {id: 4044, topic: 'f. Disloyalty', depth: 4, trackable: false},
    {id: 4045, topic: 'g. Business Judgment Rule', depth: 4, trackable: false},
    {id: 4046, topic: 'h. Liabilities and Responsibilities', depth: 4, trackable: false},
    {id: 4047, topic: 'i. Special Fact Doctrine; Inside Information', depth: 5, trackable: false},
    {id: 4048, topic: 'j. Directors Self-dealing with the Corporation', depth: 5, trackable: false},
    {id: 4049, topic: 'k. Dealings between Corporations with Interlocking Directors', depth: 5, trackable: false},
    {id: 4050, topic: '8. Capital Affairs', depth: 3, trackable: true},
    {id: 4051, topic: 'a. Certificate of Stock', depth: 4, trackable: false},
    {id: 4052, topic: 'b. Watered Stocks', depth: 4, trackable: false},
    {id: 4053, topic: 'i. Definition', depth: 5, trackable: false},
    {id: 4054, topic: 'ii. Liability of Directors', depth: 5, trackable: false},
    {id: 4055, topic: 'c. Trust Fund Doctrine', depth: 4, trackable: false},
    {id: 4056, topic: 'd. Payment of Balance of Subscription', depth: 4, trackable: false},
    {id: 4057, topic: 'e. Sale of Delinquent Shares', depth: 4, trackable: false},
    {id: 4058, topic: 'f. Transfer of Shares', depth: 4, trackable: false},
    {id: 4059, topic: 'g. Corporate Books and Records', depth: 4, trackable: false},
    {id: 4060, topic: '9. Securities – R.A. No. 8799', depth: 3, trackable: true},
    {id: 4061, topic: 'a. Regulatory Framework – Secs. 8-10', depth: 4, trackable: false},
    {id: 4062, topic: 'b. Definition of Security; Howey Test – Sec. 3', depth: 4, trackable: false},
    {id: 4063, topic: 'c. Registration of Securities', depth: 4, trackable: false},
    {id: 4064, topic: 'i. Exempt Securities', depth: 5, trackable: false},
    {id: 4065, topic: 'ii. Exempt Transactions', depth: 5, trackable: false},
    {id: 4066, topic: '10. Merger, Consolidation, and Acquisition – R.A. No. 10667', depth: 3, trackable: true},
    {id: 4067, topic: 'a. Concept – Sec. 4', depth: 4, trackable: false},
    {id: 4068, topic: 'i. Asset-only and Business Enterprise Transfers', depth: 5, trackable: false},
    {id: 4069, topic: 'b. Review – Sec. 16', depth: 4, trackable: false},
    {id: 4070, topic: 'i. Compulsory Notification – Secs. 17-19', depth: 5, trackable: false},
    {id: 4071, topic: 'ii. Prohibited Mergers and Acquisitions – Secs. 20-22', depth: 5, trackable: false},
    {id: 4072, topic: 'c. Effects', depth: 4, trackable: false},
    {id: 4073, topic: '11. Corporate Dissolution and Liquidation', depth: 3, trackable: true},
    {id: 4074, topic: '12. Foreign Corporations', depth: 3, trackable: true},
    {id: 4075, topic: 'a. Suability and Personality to Sue', depth: 4, trackable: false},
    {id: 4076, topic: 'b. Foreign Investments – R.A. No. 7042, as amended by R.A. No. 8179 and R.A. No. 11647', depth: 4, trackable: false},
    {id: 4077, topic: 'i. Doing Business in the Philippines', depth: 5, trackable: false},
    {id: 4078, topic: 'ii. Definition of Foreign Investment', depth: 5, trackable: false},
    {id: 4079, topic: 'iii. Registration Requirement', depth: 5, trackable: false},
    {id: 4080, topic: 'iv. Nationalized Activities and the Negative List', depth: 5, trackable: false},
    {id: 4081, topic: '13. Special Corporations', depth: 3, trackable: true},
    {id: 4082, topic: 'a. Close Corporations', depth: 4, trackable: false},
    {id: 4083, topic: 'b. Non-stock Corporations', depth: 4, trackable: false},
    {id: 4084, topic: 'c. Educational Corporations', depth: 4, trackable: false},
    {id: 4085, topic: 'd. Religious Corporations', depth: 4, trackable: false},
    {id: 4086, topic: 'e. One Person Corporations', depth: 4, trackable: false},
    {id: 4087, topic: 'i. Excepted Corporations', depth: 5, trackable: false},
    {id: 4088, topic: 'ii. Capital Stock Requirement', depth: 5, trackable: false},
    {id: 4089, topic: 'iii. Articles of Incorporation and By-laws', depth: 5, trackable: false},
    {id: 4090, topic: 'iv. Corporate Name', depth: 5, trackable: false},
    {id: 4091, topic: 'v. Corporate Structure and Officers', depth: 5, trackable: false},
    {id: 4092, topic: 'vi. Nominee', depth: 5, trackable: false},
    {id: 4093, topic: 'vii. Liability', depth: 5, trackable: false},
    {id: 4094, topic: 'viii. Conversion of Corporation', depth: 5, trackable: false},
    {id: 4095, topic: 'B. Partnerships', depth: 2, trackable: true},
    {id: 4096, topic: '1. General Provisions', depth: 3, trackable: true},
    {id: 4097, topic: 'a. Definition and Separate Juridical Personality', depth: 4, trackable: false},
    {id: 4098, topic: 'b. Rules to Determine Existence', depth: 4, trackable: false},
    {id: 4099, topic: 'c. Partnership by Estoppel', depth: 4, trackable: false},
    {id: 4100, topic: 'd. Kinds of Partnership', depth: 4, trackable: false},
    {id: 4101, topic: '2. Obligations of Partners among Themselves', depth: 3, trackable: true},
    {id: 4102, topic: '3. Property Rights of Partners', depth: 3, trackable: true},
    {id: 4103, topic: '4. Obligations of Partnership; Obligations of Partners to Third Persons', depth: 3, trackable: true},
    {id: 4104, topic: '5. Dissolution and Winding Up', depth: 3, trackable: true},

    // II. INSURANCE (FIXED: All 12 topics are now Depth 2 and trackable: true)
    {id: 4105, topic: 'II. INSURANCE (P.D. No. 612, as amended by R.A. No. 10607)', depth: 1, trackable: true},
    {id: 4106, topic: 'A. Concept of Insurance', depth: 2, trackable: true},
    {id: 4107, topic: 'B. Insurable Interest', depth: 2, trackable: true},
    {id: 4108, topic: 'C. Concealment', depth: 2, trackable: true},
    {id: 4109, topic: 'D. Representation', depth: 2, trackable: true},
    {id: 4110, topic: 'E. Policy', depth: 2, trackable: true},
    {id: 4111, topic: 'F. Warranties', depth: 2, trackable: true},
    {id: 4112, topic: 'G. Premium', depth: 2, trackable: true},
    {id: 4113, topic: 'H. Loss', depth: 2, trackable: true},
    {id: 4114, topic: 'I. Notice and Proof of Loss', depth: 2, trackable: true},
    {id: 4115, topic: 'J. Double Insurance and Overinsurance', depth: 2, trackable: true},
    {id: 4116, topic: 'K. Reinsurance', depth: 2, trackable: true},
    {id: 4117, topic: 'L. Rescission of Insurance Contracts', depth: 2, trackable: true},

    // III. TRANSPORTATION
    {id: 4118, topic: 'III. TRANSPORTATION', depth: 1, trackable: true},
    {id: 4119, topic: 'A. Common Carriers', depth: 2, trackable: true},
    {id: 4120, topic: '1. General Concepts', depth: 3, trackable: true},
    {id: 4121, topic: 'a. Common Carrier v. Private Carrier', depth: 4, trackable: false},
    {id: 4122, topic: 'b. Diligence Required', depth: 4, trackable: false},
    {id: 4123, topic: 'c. Transport Network Services', depth: 4, trackable: false},
    {id: 4124, topic: 'd. Defenses Available to a Common Carrier', depth: 4, trackable: false},
    {id: 4125, topic: 'B. Vigilance over Goods', depth: 2, trackable: true},
    {id: 4126, topic: '1. under the Civil Code', depth: 3, trackable: false},
    {id: 4127, topic: '2. under the Montreal Convention', depth: 3, trackable: false},
    {id: 4128, topic: '3. under the Carriage of Goods by Sea Act', depth: 3, trackable: false},
    {id: 4129, topic: 'C. Safety of Passengers', depth: 2, trackable: true},
    {id: 4130, topic: '1. under the Civil Code', depth: 3, trackable: false},
    {id: 4131, topic: '2. under the Montreal Convention', depth: 3, trackable: false},
    {id: 4132, topic: '3. under the Carriage of Goods by Sea Act', depth: 3, trackable: false},
    
    // IV. BANKING
    {id: 4133, topic: 'IV. BANKING', depth: 1, trackable: true},
    {id: 4134, topic: 'A. Secrecy of Bank Deposits – R.A. No. 1405 and R.A. No. 6426, as amended', depth: 2, trackable: true},
    {id: 4135, topic: '1. Purpose', depth: 3, trackable: false},
    {id: 4136, topic: '2. Prohibited Acts', depth: 3, trackable: false},
    {id: 4137, topic: '3. Coverage and Exceptions', depth: 3, trackable: false},
    {id: 4138, topic: '4. Garnishment of Deposits, including Foreign Deposits', depth: 3, trackable: false},
    {id: 4139, topic: 'B. General Banking Law – R.A. No. 8791', depth: 2, trackable: true},
    {id: 4140, topic: '1. Definition and Classification of Banks', depth: 3, trackable: false},
    {id: 4141, topic: '2. Distinction among Banks, Quasi-banks, and Trust Entities', depth: 3, trackable: false},
    {id: 4142, topic: '3. Nature of Bank Funds and Bank Deposits', depth: 3, trackable: false},
    {id: 4143, topic: '4. Diligence Required of Banks', depth: 3, trackable: false},
    {id: 4144, topic: '5. Prohibited Transactions by Bank Directors, Officers, and Employees', depth: 3, trackable: false},
    {id: 4145, topic: '6. Stipulation on Interest', depth: 3, trackable: false},
    {id: 4146, topic: 'C. Deposit Insurance – R.A. No. 3591, as amended by R.A. No. 11840', depth: 2, trackable: true},
    {id: 4147, topic: '1. Definition of Insured Deposit', depth: 3, trackable: false},
    {id: 4148, topic: '2. Deposit Insurance Coverage', depth: 3, trackable: false},
    {id: 4149, topic: '3. Splitting of Deposits', depth: 3, trackable: false},
    {id: 4150, topic: 'D. Anti-Money Laundering – R.A. No. 9160, as amended', depth: 2, trackable: true},
    {id: 4151, topic: '1. Policy', depth: 3, trackable: false},
    {id: 4152, topic: '2. Covered Institutions and their Obligations', depth: 3, trackable: false},
    {id: 4153, topic: '3. Covered Transactions', depth: 3, trackable: false},
    {id: 4154, topic: '4. Suspicious Transactions', depth: 3, trackable: false},
    {id: 4155, topic: '5. Safe Harbor Provision', depth: 3, trackable: false},
    {id: 4156, topic: '6. Money Laundering', depth: 3, trackable: true},
    {id: 4157, topic: 'a. How Committed', depth: 4, trackable: false},
    {id: 4158, topic: 'b. Predicate Crimes or Unlawful Activity', depth: 4, trackable: false},
    {id: 4159, topic: '7. Authority to Inquire, Freezing, and Forfeiture', depth: 3, trackable: false},
    {id: 4160, topic: 'E. The Central Bank – R.A. No. 7653, as amended by R.A. No. 11211', depth: 2, trackable: true},
    {id: 4161, topic: '1. State Policies', depth: 3, trackable: false},
    {id: 4162, topic: '2. Powers and Functions of the Monetary Board', depth: 3, trackable: false},
    {id: 4163, topic: '3. Banks in Distress', depth: 3, trackable: true},
    {id: 4164, topic: 'a. Conservatorship', depth: 4, trackable: false},
    {id: 4165, topic: 'b. Closure', depth: 4, trackable: false},
    {id: 4166, topic: 'c. Receivership', depth: 4, trackable: false},
    {id: 4167, topic: 'd. Liquidation', depth: 4, trackable: false},
    
    // V. INTELLECTUAL PROPERTY
    {id: 4168, topic: 'V. INTELLECTUAL PROPERTY – R.A. No. 8293, as amended', depth: 1, trackable: true},
    {id: 4169, topic: 'A. Patents', depth: 2, trackable: true},
    {id: 4170, topic: '1. Patentable v. Non-patentable Inventions', depth: 3, trackable: false},
    {id: 4171, topic: '2. Ownership of a Patent', depth: 3, trackable: false},
    {id: 4172, topic: '3. Rights Conferred', depth: 3, trackable: false},
    {id: 4173, topic: '4. Limitations', depth: 3, trackable: false},
    {id: 4174, topic: '5. Infringement', depth: 3, trackable: false},
    {id: 4175, topic: '6. Cancellation', depth: 3, trackable: false},
    {id: 4176, topic: '7. True and Actual Inventor\'s Remedy', depth: 3, trackable: false},
    {id: 4177, topic: '8. Licensing', depth: 3, trackable: false},
    {id: 4178, topic: '9. Assignment and Transmission of Rights', depth: 3, trackable: false},
    {id: 4179, topic: 'B. Trademarks', depth: 2, trackable: true},
    {id: 4180, topic: '1. Marks v. Collective Marks v. Trade Names', depth: 3, trackable: false},
    {id: 4181, topic: '2. Acquisition of Ownership', depth: 3, trackable: false},
    {id: 4182, topic: '3. Non-registrable Marks', depth: 3, trackable: false},
    {id: 4183, topic: '4. Ownership, Registration, and Duration', depth: 3, trackable: false},
    {id: 4184, topic: '5. Confusing Similarity', depth: 3, trackable: false},
    {id: 4185, topic: '6. Well-known Marks', depth: 3, trackable: false},
    {id: 4186, topic: '7. Rights Conferred by Registration', depth: 3, trackable: false},
    {id: 4187, topic: '8. Infringement', depth: 3, trackable: false},
    {id: 4188, topic: '9. Unfair Competition', depth: 3, trackable: false},
    {id: 4189, topic: '10. Cancellation', depth: 3, trackable: false},
    {id: 4190, topic: 'C. Copyright', depth: 2, trackable: true},
    {id: 4191, topic: '1. Basic Principles – Secs. 172.2, 175, and 181', depth: 3, trackable: false},
    {id: 4192, topic: '2. Copyrightable Works', depth: 3, trackable: false},
    {id: 4193, topic: '3. Non-copyrightable Works', depth: 3, trackable: false},
    {id: 4194, topic: '4. Rights Conferred by Copyright', depth: 3, trackable: false},
    {id: 4195, topic: '5. Ownership of a Copyright', depth: 3, trackable: false},
    {id: 4196, topic: '6. Limitations on Copyright', depth: 3, trackable: false},
    {id: 4197, topic: '7. Fair Use', depth: 3, trackable: false},
    {id: 4198, topic: '8. Copyright Infringement', depth: 3, trackable: false},
    
    // VI. SPECIAL COMMERCIAL LAWS
    {id: 4199, topic: 'VI. SPECIAL COMMERCIAL LAWS', depth: 1, trackable: true},
    {id: 4200, topic: 'A. R.A. No. 10142 (Financial Rehabilitation and Insolvency Act)', depth: 2, trackable: true},
    {id: 4201, topic: '1. Definition of Insolvent', depth: 3, trackable: false},
    {id: 4202, topic: '2. Rehabilitation', depth: 3, trackable: true},
    {id: 4203, topic: 'a. Key Concepts', depth: 4, trackable: false},
    {id: 4204, topic: 'b. Effects of Commencement Order and Exceptions', depth: 4, trackable: false},
    {id: 4205, topic: 'c. Cram Down Effect', depth: 4, trackable: false},
    {id: 4206, topic: '3. Liquidation and Effects of Liquidation Order', depth: 3, trackable: false},
    {id: 4207, topic: '4. Suspension of Payments', depth: 3, trackable: false},
    {id: 4208, topic: 'B. R.A. No. 8792 (Electronic Commerce Act)', depth: 2, trackable: true},
    {id: 4209, topic: '1. Legal Recognition of Electronic Data Messages, Documents, and Signatures – Secs. 6-11', depth: 3, trackable: false},
    {id: 4210, topic: '2. Lawful Access and Obligation of Confidentiality – Sec. 32', depth: 3, trackable: false},
    {id: 4211, topic: 'C. Commonwealth Act No. 146, as amended by R.A. No. 11659 (Public Service Act)', depth: 2, trackable: true},
    {id: 4212, topic: '1. Critical Infrastructure – R.A. No. 11659, Sec. 2(e)', depth: 3, trackable: false},
    {id: 4213, topic: '2. Foreign State-owned Enterprise – R.A. No. 11659, Sec. 2(g)', depth: 3, trackable: false},
    {id: 4214, topic: '3. Public Service as Public Utility – R.A. No. 11659, Sec. 4', depth: 3, trackable: false},
    {id: 4215, topic: '4. Unlawful Acts – R.A. No. 11659, Sec. 9', depth: 3, trackable: false},
    {id: 4216, topic: '5. Suspensive and Prohibitory Powers of the President – R.A. No. 11659, Sec. 23', depth: 3, trackable: false},
    {id: 4217, topic: '6. Investments by an Entity Controlled by or Acting on Behalf of a Foreign Government, or Foreign State-Owned Enterprises – R.A. No. 11659, Sec. 24', depth: 3, trackable: false},
    {id: 4218, topic: '7. Reciprocity Clause – R.A. No. 11659, Sec. 25', depth: 3, trackable: false},
    {id: 4219, topic: 'D. R.A. No. 10667 (Philippine Competition Act)', depth: 2, trackable: true},
    {id: 4220, topic: '1. Definitions and Scope of Application – Sec. 4', depth: 3, trackable: false},
    {id: 4221, topic: '2. Prohibited Acts', depth: 3, trackable: true},
    {id: 4222, topic: 'a. Anti-competitive Agreements – Sec. 14', depth: 4, trackable: true},
    {id: 4223, topic: 'i. Per Se Violations', depth: 5, trackable: false},
    {id: 4224, topic: 'ii. Not Per Se Violations', depth: 5, trackable: false},
    {id: 4225, topic: 'b. Abuse of Dominant Position – Sec. 15', depth: 4, trackable: false},
    {id: 4226, topic: '3. Determining the Relevant Market – Secs. 4(k) and 24', depth: 3, trackable: false},
    {id: 4227, topic: '4. Determining Control or Dominance of Market – Secs. 25 and 27', depth: 3, trackable: false},
    {id: 4228, topic: '5. Determining Existence of Anti-competitive Conduct – Secs. 26', depth: 3, trackable: false},
    
    // VII. TAXATION LAW
    {id: 4229, topic: 'VII. TAXATION LAW', depth: 1, trackable: true},
    {id: 4230, topic: 'A. General Principles', depth: 2, trackable: true},
    {id: 4231, topic: '1. Concept and Definition of Taxation', depth: 3, trackable: false},
    {id: 4232, topic: '2. Inherent and Constitutional Limitations of Taxation', depth: 3, trackable: false},
    {id: 4233, topic: '3. Requisites of a Valid Tax', depth: 3, trackable: false},
    {id: 4234, topic: '4. Lifeblood Doctrine; Manifestations; Prohibition on Compensation and Set-off, Impact, and Effect', depth: 3, trackable: false},
    {id: 4235, topic: '5. Authority of Congress, Secretary of Finance, and Commissioner of Internal Revenue (CIR)', depth: 3, trackable: false},
    {id: 4236, topic: '6. Construction and Interpretation of Tax Laws, Rules, and Regulations', depth: 3, trackable: false},
    {id: 4237, topic: '7. Double Taxation', depth: 3, trackable: false},
    {id: 4238, topic: '8. Escape from Taxation', depth: 3, trackable: false},
    {id: 4239, topic: '9. Tax Exemption', depth: 3, trackable: false},
    {id: 4240, topic: '10. Compromise and Tax Amnesty', depth: 3, trackable: false},
    {id: 4241, topic: '11. Taxpayer’s Suit: Rationale and Requisites', depth: 3, trackable: false},
    
    {id: 4242, topic: 'B. National Taxation – NIRC', depth: 2, trackable: true},
    {id: 4243, topic: '1. Jurisdiction, Powers, and Functions of the Bureau of Internal Revenue', depth: 3, trackable: false},
    {id: 4244, topic: '2. Income Tax', depth: 3, trackable: true},
    {id: 4245, topic: 'a. Nature and General Principles', depth: 4, trackable: true},
    {id: 4246, topic: 'i. Criteria in Imposing Philippine Income Tax', depth: 5, trackable: false},
    {id: 4247, topic: 'ii. Kinds of Taxpayers', depth: 5, trackable: false},
    {id: 4248, topic: 'b. Income', depth: 4, trackable: true},
    {id: 4249, topic: 'i. Definition', depth: 5, trackable: false},
    {id: 4250, topic: 'ii. Realization and Recognition', depth: 5, trackable: false},
    {id: 4251, topic: 'iii. Taxability', depth: 5, trackable: false},
    {id: 4252, topic: 'iv. Sources', depth: 5, trackable: true},
    {id: 4253, topic: '(a) Compensation Income', depth: 6, trackable: false},
    {id: 4254, topic: '(b) Professional Income', depth: 6, trackable: false},
    {id: 4255, topic: '(c) Income from Business', depth: 6, trackable: true},
    {id: 4256, topic: '1) Active v. Passive Income', depth: 7, trackable: false},
    {id: 4257, topic: '(d) Income from Dealings in Property', depth: 6, trackable: true},
    {id: 4258, topic: '1) Capital v. Ordinary Asset', depth: 7, trackable: false},
    {id: 4259, topic: 'v. Situs of Income Taxation', depth: 5, trackable: false},
    {id: 4260, topic: 'vi. Gross Income v. Net Income v. Taxable Income', depth: 5, trackable: true},
    {id: 4261, topic: '(a) Tax Deductions v. Tax Credits', depth: 6, trackable: false},
    {id: 4262, topic: '(b) Optional Standard Deduction', depth: 6, trackable: false},
    {id: 4263, topic: 'c. Withholding Taxes', depth: 4, trackable: true},
    {id: 4264, topic: 'i. Rationale', depth: 5, trackable: false},
    {id: 4265, topic: 'ii. Creditable v. Withholding Taxes', depth: 5, trackable: false},
    {id: 4266, topic: 'iii. Duties of a Withholding Agent', depth: 5, trackable: false},
    {id: 4267, topic: '3. Value-Added Tax (VAT)', depth: 3, trackable: true},
    {id: 4268, topic: 'a. Concept', depth: 4, trackable: false},
    {id: 4269, topic: 'b. Elements of Transaction Subject to VAT', depth: 4, trackable: false},
    {id: 4270, topic: 'c. Impact and Incidence of Tax', depth: 4, trackable: false},
    {id: 4271, topic: 'd. Destination Principle; Cross-Border Doctrine', depth: 4, trackable: false},
    {id: 4272, topic: 'e. Transactions Deemed Sale Subject to VAT', depth: 4, trackable: false},
    {id: 4273, topic: 'f. Zero-rated Transactions', depth: 4, trackable: false},
    {id: 4274, topic: 'g. VAT Exempt Persons v. VAT Exempt Transactions', depth: 4, trackable: false},
    {id: 4275, topic: 'h. Input and Output Tax', depth: 4, trackable: false},
    {id: 4276, topic: 'i. Tax Refund or Tax Credit', depth: 4, trackable: false},
    {id: 4277, topic: '4. Estate Tax (Basic Principles and Concepts only)', depth: 3, trackable: false},
    {id: 4278, topic: '5. Donor’s Tax (Basic Principles and Concepts only)', depth: 3, trackable: false},
    {id: 4279, topic: '6. Tax Remedies under the NIRC', depth: 3, trackable: true},
    {id: 4280, topic: 'a. General Concepts', depth: 4, trackable: true},
    {id: 4281, topic: 'i. Tax Deficiency v. Tax Delinquency', depth: 5, trackable: false},
    {id: 4282, topic: 'ii. Tax Evasion', depth: 5, trackable: false},
    {id: 4283, topic: 'b. Civil Penalties', depth: 4, trackable: true},
    {id: 4284, topic: 'i. Deficiency Interest and Delinquency Interest', depth: 5, trackable: false},
    {id: 4285, topic: 'ii. Surcharge', depth: 5, trackable: false},
    {id: 4286, topic: 'iii. Compromise Penalty', depth: 5, trackable: false},
    {id: 4287, topic: 'c. Assessment Process', depth: 4, trackable: true},
    {id: 4288, topic: 'i. Letter of Authority', depth: 5, trackable: false},
    {id: 4289, topic: 'ii. Submission of Supporting Documents by Taxpayer', depth: 5, trackable: false},
    {id: 4290, topic: 'iii. Notice of Discrepancy', depth: 5, trackable: false},
    {id: 4291, topic: 'iv. Issuance of Preliminary Assessment Notice', depth: 5, trackable: false},
    {id: 4292, topic: 'v. Issuance of Formal Letter of Demand or Final Assessment Notice', depth: 5, trackable: true},
    {id: 4293, topic: '(a) Prescriptive Period for Assessment', depth: 6, trackable: true},
    {id: 4294, topic: '1) False Return v. Fraudulent Return v. Non-filing', depth: 7, trackable: false},
    {id: 4295, topic: '(b) Suspension of the Running of Statute of Limitations', depth: 6, trackable: false},
    {id: 4296, topic: 'd. Collection Process', depth: 4, trackable: true},
    {id: 4297, topic: 'i. Requisites', depth: 5, trackable: false},
    {id: 4298, topic: 'ii. Prescriptive Periods', depth: 5, trackable: false},
    {id: 4299, topic: 'e. Taxpayers\' Remedies', depth: 4, trackable: true},
    {id: 4300, topic: 'i. Protesting an Assessment', depth: 5, trackable: true},
    {id: 4301, topic: '(a) Period to File Protest', depth: 6, trackable: false},
    {id: 4302, topic: '(b) Effect of Failure to File Protest', depth: 6, trackable: false},
    {id: 4303, topic: 'ii. Submission of Supporting Documents by Taxpayer', depth: 5, trackable: false},
    {id: 4304, topic: 'iii. Decision of the Commissioner on the Protest', depth: 5, trackable: true},
    {id: 4305, topic: '(a) Period to Act Upon or Decide', depth: 6, trackable: false},
    {id: 4306, topic: '(b) Remedies in Case of CIR’s Denial or Failure to Act', depth: 6, trackable: false},
    {id: 4307, topic: '(c) Effect of Failure to Appeal', depth: 6, trackable: false},
    {id: 4308, topic: 'iv. Compromise and Abatement of Taxes', depth: 5, trackable: false},
    {id: 4309, topic: 'v. Recovery of Tax Erroneously or Illegally Collected', depth: 5, trackable: true},
    {id: 4310, topic: '(a) Grounds, Requisites, and Period for Filing a Claim for Refund or Issuance of a Tax Credit Certificate', depth: 6, trackable: false},
    {id: 4311, topic: '(b) Proper Party to File Claim for Refund or Tax Credit', depth: 6, trackable: false},
    {id: 4312, topic: 'f. Government Remedies', depth: 4, trackable: true},
    {id: 4313, topic: 'i. Administrative Remedies', depth: 5, trackable: true},
    {id: 4314, topic: '(a) Tax Lien', depth: 6, trackable: false},
    {id: 4315, topic: '(b) Distraint and Levy', depth: 6, trackable: false},
    {id: 4316, topic: '(c) Forfeiture of Real Property', depth: 6, trackable: false},
    {id: 4317, topic: '(d) Suspension of Business Operation', depth: 6, trackable: false},
    {id: 4318, topic: 'ii. Judicial Remedies', depth: 5, trackable: true},
    {id: 4319, topic: '(a) Civil Action', depth: 6, trackable: false},
    {id: 4320, topic: '(b) Criminal Action', depth: 6, trackable: false},
    
    {id: 4321, topic: 'C. Local Taxation – R.A. No. 7160', depth: 2, trackable: true},
    {id: 4322, topic: '1. General Principles – Secs. 130 and 132', depth: 3, trackable: false},
    {id: 4323, topic: '2. Common Limitations on the Taxing Powers of Local Government Units – Secs. 133', depth: 3, trackable: false},
    {id: 4324, topic: '3. Validity of Local Tax Ordinance – Sec. 187', depth: 3, trackable: false},
    {id: 4325, topic: '4. Assessment and Collection of Local Taxes', depth: 3, trackable: true},
    {id: 4326, topic: 'a. Remedies of Local Government Units', depth: 4, trackable: false},
    {id: 4327, topic: 'b. Prescriptive Period', depth: 4, trackable: false},
    {id: 4328, topic: 'c. Injunction', depth: 4, trackable: false},
    {id: 4329, topic: '5. Taxpayers\' Remedies', depth: 3, trackable: true},
    {id: 4330, topic: 'a. Protest – Sec. 195', depth: 4, trackable: false},
    {id: 4331, topic: 'b. Refund or Credit – Sec. 196', depth: 4, trackable: false},
    {id: 4332, topic: 'c. Court Action', depth: 4, trackable: false},
    {id: 4333, topic: '6. Local Taxes', depth: 3, trackable: true},
    {id: 4334, topic: 'a. Professional Tax – Sec. 139', depth: 4, trackable: false},
    {id: 4335, topic: 'b. Local Business Tax – Secs. 143, 145, and 146', depth: 4, trackable: false},
    {id: 4336, topic: 'c. Community Tax – Secs. 157-160', depth: 4, trackable: false},
    {id: 4337, topic: 'd. Real Property Taxation (Book II, Title II)', depth: 4, trackable: true},
    {id: 4338, topic: 'i. Fundamental Principles; Nature; Power to Levy', depth: 5, trackable: false},
    {id: 4339, topic: 'ii. Exemption from Real Property Tax – Sec. 234', depth: 5, trackable: false},
    {id: 4340, topic: 'iii. Appraisal and Assessment', depth: 5, trackable: false},
    {id: 4341, topic: 'iv. Collection', depth: 5, trackable: false},
    {id: 4342, topic: 'v. Taxpayers\' Remedies', depth: 5, trackable: true},
    {id: 4343, topic: '(a) Against Assessment', depth: 6, trackable: true},
    {id: 4344, topic: '1) Payment Under Protest; Exceptions', depth: 7, trackable: false},
    {id: 4345, topic: '2) Compromise of Assessment', depth: 7, trackable: false},
    {id: 4346, topic: '(b) Against Valuation of Property', depth: 6, trackable: false},
    {id: 4347, topic: 'vi. Judicial Remedies', depth: 5, trackable: true},
    {id: 4348, topic: '(a) Appeal to the Local Board of Assessment Appeals', depth: 6, trackable: false},
    {id: 4349, topic: '(b) Appeal to the Central Board of Assessment Appeals', depth: 6, trackable: false},
    {id: 4350, topic: '(c) Effect of Payment of Taxes', depth: 6, trackable: false},
    
    {id: 4351, topic: 'D. Judicial Remedies', depth: 2, trackable: true},
    {id: 4352, topic: '1. Court of Tax Appeals (CTA)', depth: 3, trackable: true},
    {id: 4353, topic: 'a. Exclusive Original and Appellate Jurisdiction Over Civil Cases', depth: 4, trackable: false},
    {id: 4354, topic: 'b. Exclusive Original and Appellate Jurisdiction Over Criminal Cases', depth: 4, trackable: false},
    {id: 4355, topic: '2. Procedures', depth: 3, trackable: true},
    {id: 4356, topic: 'a. Action for Collection of Taxes', depth: 4, trackable: true},
    {id: 4357, topic: 'i. National Taxes', depth: 5, trackable: false},
    {id: 4358, topic: 'ii. Local Taxes', depth: 5, trackable: false},
    {id: 4359, topic: 'b. Civil Cases', depth: 4, trackable: true},
    {id: 4360, topic: 'i. Who May Appeal, Mode of Appeal, and Effect of Appeal', depth: 5, trackable: false},
    {id: 4361, topic: 'ii. Suspension of Collection of Taxes', depth: 5, trackable: false},
    {id: 4362, topic: 'iii. Injunction Not Available to Restrain Tax Collection', depth: 5, trackable: false},
    {id: 4363, topic: 'c. Criminal Cases', depth: 4, trackable: true},
    {id: 4364, topic: 'i. Institution and Prosecution of Criminal Action', depth: 5, trackable: false},
    {id: 4365, topic: 'ii. Institution of Civil Action in Criminal Action', depth: 5, trackable: false},
    {id: 4366, topic: 'iii. Period to Appeal', depth: 5, trackable: false},
    {id: 4367, topic: '3. Appeal to the CTA En Banc', depth: 3, trackable: false},
    {id: 4368, topic: '4. Petition for Review on Certiorari to the Supreme Court', depth: 3, trackable: false}
];

// 2. Storage Key and Subject Details
const SYLLABUS_STORAGE_KEY_COMM = 'comm_tax_progress';
const SUBJECT_NAME_COMM = 'comm';
const SUBJECT_TITLE_COMM = 'COMMERCIAL AND TAXATION LAWS (20%)';
const SUBJECT_ICON_COMM = 'banknote';

// 3. Create Logic Instance
// This calls the global factory defined in index.html
const COMM_LOGIC = window.createSyllabusLogic(SUBJECT_NAME_COMM, COMM_TAX_SYLLABUS, SYLLABUS_STORAGE_KEY_COMM, SUBJECT_ICON_COMM, SUBJECT_TITLE_COMM);

// 4. Inject Panel HTML into the main container in index.html
document.addEventListener('DOMContentLoaded', () => {
    const container = document.getElementById('subject-trackers-container');
    if (container) {
        // Only inject if the base logic module hasn't already done it (prevents duplication during load)
        if (!document.getElementById(`subject-tracker-panel-${SUBJECT_NAME_COMM}`)) {
            container.innerHTML += COMM_LOGIC.getPanelHtml(SUBJECT_NAME_COMM, SUBJECT_TITLE_COMM, SUBJECT_ICON_COMM);
        }
    }
});

// 5. Expose Logic Globally (needed for index.html onload to attach to map)
window.createCOMM_LOGIC = () => COMM_LOGIC;
